#!/usr/bin/python
# -*- coding: UTF-8 -*-

"""
Copyright (C) 2009 Jordi Sanfeliu

Licensed under the GNU General Public License Version 2

This program is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public License as published by the Free Software
Foundation; either version 2 of the License, or (at your option) any later
version.

This program is distributed in the hope that it will be useful, but WITHOUT
ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
more details.

You should have received a copy of the GNU General Public License along
with this program; if not, write to the Free Software Foundation, Inc., 51
Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.

=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Jordi Sanfeliu <jordi@fibranet.cat>
http://www.monitorix.org
"""

from pymonitorix.Main import Main

def main():
	try:
		from pymonitorix import config
		datadir = config.datadir
	except:
		datadir = '.'
	app = Main(datadir)
	app.main()

if __name__ == "__main__":
	main()

